# Server yapılandırması
server:
  port: 8080
  mode: development # development, production

# Veritabanı yapılandırması
database:
  driver: "{DATABASE_DRIVER}"
  host: "{POSTGRES_HOST}"
  port: 5432
  user: "{POSTGRES_USER}"
  password: "{POSTGRES_PASSWORD}"
  dbname: "{POSTGRES_DB}"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h

# JWT yapılandırması
jwt:
  secret: "{JWT_SECRET}" # More secure random value
  access_token_expiration: "{ACCESS_TOKEN_EXPIRATION}" # Access token should be short-lived
  refresh_token_expiration: "{REFRESH_TOKEN_EXPIRATION}" # 30 days for refresh token
  issuer: "{ISSUER}"

# Loglama yapılandırması
logging:
  level: debug # debug, info, warn, error
  format: text # text, json 

# SMTP Email yapılandırması (Email doğrulama için)
smtp:
  host: "{SMTP_HOST}" # smtp.gmail.com, smtp.office365.com, etc.
  port: 587 # 587 (TLS), 465 (SSL), 25 (non-secure)
  username: "{SMTP_USERNAME}" # email address
  password: "{SMTP_PASSWORD}" # email password or app password
  from_name: "UniSphere" # Sender name
  from_email: "{FROM_EMAIL}" # noreply@unisphere.app
  use_tls: true # true for TLS, false for non-TLS